### PR TITLE
add my polybar config

### PR DESCRIPTION
**Pull request by RedBlizard**
files uploaded again

### CODE REVIEW

**Comment by RedBlizard** [comment]
files are uploaded with add files

**Comment by dalto8** [comment]
Do you need some help?  I am not sure exactly what you are trying to accomplish but you have two PRs open which appear to have the same thing with different naming.

This one seems cleaner than #6 does.

**Comment by RedBlizard** [comment]
trying to get my polybar folder with configs to show up here
ScreenShot_2022-12-10_at_01:01:17-PM

**Comment by dalto8** [comment]
It won't show up there until someone merges it.

Basically, a PR is a request to add something to the repo.  You make the request, and then once it is reviewed and approved, it gets added(merged).

Currently, you have two separate requests open.

**Comment by RedBlizard** [comment]
just closed 1 pull request there shoot  be only one open now.

**Comment by RedBlizard** [comment]
I see know only 1 pull request open, hope it is okay now , my polybar config files are uploaded

**Comment by dalto8** [comment]
Yes, now you just need to wait for it to be reviewed.

On that note, I am not really a polybar expert but it looks like this config has several bspwn specific elements in it.  I will defer to @killajoe if that is a problem or not.

**Comment by RedBlizard** [comment]
No dalto that is not a problem, it is indeed a bspwm only polybar config i do not use i3 or dwm or any other window manager. but if needed i can edit the i3 part in de config that is no problem.

**Comment by killajoe** [comment]
Yes now it looks good to me..

**Pull request merged**
